# Generated by Django 5.0.3 on 2024-06-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
